name: Docker Build

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/my-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        run: docker build -t my-service:latest .
